# Task1

In [1]:
import pandas as pd
import numpy as np

In [17]:
a= np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10,7]])


In [18]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [28]:
mean_a=np.mean(a,axis=1)
mean_a

array([2. , 8.4])

In [30]:
mean_a=mean_a.reshape(2,1)

In [31]:
np.shape(mean_a)

(2, 1)

# Task2

In [34]:
a_centered=a-mean_a
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

# Task3

In [38]:
a_centered_sp=np.dot(a_centered[0],a_centered[1])

In [47]:
N=len(a[1])
a_centered_sp=a_centered_sp/(N-1)

In [48]:
a_centered_sp

2.0

# Task4

In [55]:
Covariation=np.cov(a)

In [56]:
cov=Covariation[0,1]

In [57]:
cov

2.0